name: Unit Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install Poetry
        run: pipx install poetry
        shell: bash

      - name: Install dependencies
        run: poetry install --with dev
        shell: bash

      - name: Run linter
        run: poetry run pylint scripts/ --output-format=colorized
        continue-on-error: true

      - name: Run tests
        run: poetry run pytest tests/ -v --tb=short
